DROP DATABASE IF EXISTS bank_appli;

create DATABASE bank_appli;

USE bank_appli;

CREATE TABLE T_R_TYPEACCOUNT_TAC(
   TAC_ID INT NOT NULL AUTO_INCREMENT,
   TAC_NUMBER INT NOT NULL,
   TAC_LABEL VARCHAR(50) NOT NULL,
   PRIMARY KEY(TAC_ID)
);

CREATE TABLE T_R_TYPEOPERATION_TOP(
   TOP_ID INT NOT NULL AUTO_INCREMENT,
   TOP_NUMBER INT NOT NULL,
   TOP_LABEL VARCHAR(50) NOT NULL,
   PRIMARY KEY(TOP_ID),
   UNIQUE(TOP_NUMBER)
);

CREATE TABLE T_ACCOUNT_ACC(
   ACC_ID INT NOT NULL AUTO_INCREMENT,
   ACC_NUMBER INT NOT NULL,
   ACC_BALANCE FLOAT NOT NULL,
   ACC_CREATE_AT TIMESTAMP,
   ACC_UPDATE_AT TIMESTAMP,
   ACC_OVERDRAFT INT,
   ACC_INTEREST_RATE FLOAT,
   TAC_ID INT NOT NULL,
   PRIMARY KEY(ACC_ID),
   UNIQUE(ACC_NUMBER),
   CONSTRAINT FK_T_ACCOUNT_ACC_T_R_TYPEACCOUNT_TAC
   FOREIGN KEY(TAC_ID) 
   REFERENCES T_R_TYPEACCOUNT_TAC(TAC_ID)
);

CREATE TABLE T_OPERATION_OPE(
   OPE_ID INT NOT NULL AUTO_INCREMENT,
   OPE_description VARCHAR(50) NOT NULL,
   OPE_date TIMESTAMP,
   OPE_amount FLOAT NOT NULL,
   ACC_ID INT NOT NULL,
   TOP_ID INT NOT NULL,
   PRIMARY KEY(OPE_ID),
   CONSTRAINT FK_T_OPERATION_OPE_T_ACCOUNT_ACC
   FOREIGN KEY(ACC_ID)
   REFERENCES T_ACCOUNT_ACC(ACC_ID),
   CONSTRAINT FK_T_OPERATION_OPE_T_R_TYPEOPERATION_TOP
   FOREIGN KEY(TOP_ID)
   REFERENCES T_R_TYPEOPERATION_TOP(TOP_ID)
);
